### ISSUE TITLE
root-reprovision.filesystem-only is failing with Failed to stat /dev/disk/by-uuid/...

### ISSUE THREAD

**Issue by ravanelli** [openshift/os#578] opened 2021-07-12 17:36 UTC
The kola test config.root-reprovision.filesystem-only is failing in the pipelines with  Failed to stat /dev/disk/by-uuid/f4020372-9575-4c49-842c-3f2d0f51b10f: No such file or directory 

```
[   40.553374] ignition[692]: disks: createFilesystems: found ext4 filesystem at "/dev/disk/by-label/root" with uuid "f4020372-9575-4c49-842c-3f2d0f51b10f" and label "root"
...
...
[   41.043273] systemd[1]: Starting File System Check on /dev/disk/by-uuid/f4020372-9575-4c49-842c-3f2d0f51b10f...
[   41.258542] ignition-ostree-transposefs[704]: Mounting /dev/disk/by-label/root (/dev/vda4) to /sysroot
[   41.323240] EXT4-fs (vda4): mounted filesystem with ordered data mode. Opts: (null)
[   41.450573] systemd-fsck[703]: Failed to stat /dev/disk/by-uuid/f4020372-9575-4c49-842c-3f2d0f51b10f: No such file or directory
```

**Comment by cgwalters** [comment] 2021-07-12 17:42
My initial thought was this started failing after https://github.com/openshift/os/pull/576 but I notice in the CI logs that that test did pass there.  Ideas for next steps

- Check if this reproduces locally
- Try reverting that PR
- Verify a dummy PR here still works

**Comment by cgwalters** [comment] 2021-07-12 17:59
Another possibility here is that something changed recently in the RHEL content going into the 4.9 builds (systemd/udev?).

**Comment by ravanelli** [comment] 2021-07-12 18:31
Thanks @cgwalters! 
I will test it locally to see.

Not sure if may be related or not, the `coreos.ignition.once` is also failing. The etc/ignition-ran is recreated after the reboot causing the test to fail. I should probably open another issue to track it.

**Comment by miabbott** [comment] 2021-07-13 14:08
I built RHCOS 4.9 locally using `cosa:rhcos-4.8` and successfully ran `cosa kola run`:

`--- PASS: ext.config.root-reprovision.filesystem-only (65.91s)`

**Comment by miabbott** [comment] 2021-07-13 14:20
Looking at the last couple of failures from the internal pipeline, there are multiple failures being observed:

```
--- FAIL: luks.tang (778.52s)
--- FAIL: luks.sss.t1 (777.39s)
--- FAIL: luks.sss.t2 (781.47s)
--- FAIL: ext.config.root-reprovision.filesystem-only (979.22s)
--- FAIL: coreos.ignition.once (66.16s)
```

Sometimes the job times out when running `rpmostree.install-uninstall/install` with a failure like:

`Jul 13 11:15:33 ignition[822]: }CRITICAL : Ignition failed: failed to create files: failed to create files: error creating /sysroot/etc/yum.repos.d/epel.repo: error creating file "/sysroot/etc/yum.repos.d/epel.repo": A file exists there already and overwrite is false`

Going back to the oldest failure available in Jenkins (and shared with the most recent failure), one package change that keeps appearing is this:

```
Upgraded:
  ignition 2.11.0-1.rhaos4.9.el8 -> 2.11.0-2.rhaos4.9.el8
```

I believe this includes the spec stabilization for Ignition spec v3.3.0; perhaps this new version of Ignition isn't working as expected?

**Comment by miabbott** [comment] 2021-07-13 14:37
> Sometimes the job times out when running `rpmostree.install-uninstall/install` with a failure like:
> 
> `Jul 13 11:15:33 ignition[822]: }CRITICAL : Ignition failed: failed to create files: failed to create files: error creating /sysroot/etc/yum.repos.d/epel.repo: error creating file "/sysroot/etc/yum.repos.d/epel.repo": A file exists there already and overwrite is false`

From the console logs related to this particular failing test, it looks like `ignition.firstboot` is not being removed from the kernel command line before the system is rebooted, so Ignition keeps trying to run (which explains why the file keeps trying to be written)

```
$ grep BOOT_IMAGE rpmostree.install-uninstall/7dcdf6c8-db08-452c-9278-cd57447c15d3/console.txt  | more
[    0.000000] Command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.1/rhcos/d34f1d24f02de1e4737b793f
ad8168cded17ddfb2b1dac7525c8fac5928ee024/0
[    0.000000] Kernel command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.1/rhcos/d34f1d24f02de1e47
37b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/0
[    0.000000] Command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e4737b793f
ad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Kernel command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e47
37b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[   17.823290] dracut-cmdline[1023]: Using kernel command line parameters: ip=dhcp,dhcp6 rd.driver.pre=dm_multipath BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.p
latform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e4737b793f
ad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Kernel command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e47
37b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e4737b793f
ad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Kernel command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e47
37b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e4737b793f
ad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Kernel command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e47
37b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e4737b793f
ad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Kernel command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e47
37b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e4737b793f
ad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Kernel command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e47
37b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e4737b793f
ad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Kernel command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e47
37b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e4737b793f
ad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Kernel command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e47
37b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e4737b793f
ad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Kernel command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e47
37b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e4737b793f
ad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Kernel command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e47
37b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e4737b793f
ad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
[    0.000000] Kernel command line: BOOT_IMAGE=(hd0,gpt3)/ostree/rhcos-d34f1d24f02de1e4737b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/vmlinuz-4.18.0-305.7.1.el8_4.x86_64 random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ignition.firstboot ostree=/ostree/boot.0/rhcos/d34f1d24f02de1e47
37b793fad8168cded17ddfb2b1dac7525c8fac5928ee024/0 root=UUID=df2e83e8-e0b6-4639-a89e-00cc96a75432 rw rootflags=prjquota
```

**Comment by miabbott** [comment] 2021-07-13 15:05
There was a MR to the internal RHCOS config repo that bumps `fedora-coreos-config` for the Ignition service move; I suspect the failures we are seeing are related to that move.

The MR was just merged, so we will soon see if the failures are resolved by that.

**Comment by ravanelli** [comment] 2021-07-13 15:35
I did a new build in this meantime with ` ignition-2.11.0-1.rhaos4.9.el8.ppc64le (coreos-assembler-local-overrides)`:

```
sh-5.0# kola run coreos.ignition.once
=== RUN   coreos.ignition.once
--- PASS: coreos.ignition.once (103.68s)
PASS, output in tmp/kola/qemu-unpriv-2021-07-13-1528-54254
```
Thanks for help @miabbott =)

**Comment by miabbott** [comment] 2021-07-13 16:08
Early results in the job building the downstream MR show that `kola run` has passed...I think we'll be able to close this once the build completes successfully.

**Comment by cgwalters** [comment] 2021-07-13 16:29
Hopefully soon then problems like this will entirely go away when the pipeline reads this git repo directly.

**Comment by miabbott** [comment] 2021-07-13 19:47
> Early results in the job building the downstream MR show that `kola run` has passed...I think we'll be able to close this once the build completes successfully.

The downstream 4.9 build was ultimately successful; I'm going to close this issue.

**Closed by miabbott** 2021-07-13 19:47 UTC
