### ISSUE TITLE
unable to start NFS services after reboot

### ISSUE THREAD

**Issue by arithx** [openshift/os#379] opened 2019-03-11 21:09 UTC
After rebooting post-pivot NFS is broken. Initially discovered while developing `oscontainer` support into `kola`.

Initial Version: `400.7.20190301.0`
OSContainer Version being `pivot`'d into: `400.7.20190306.0`
Additional Notes: Specifically `var-lib-nfs-rpc_pipefs.mount` shows as `active (mounted)`, however, `nfs-idmapd.service` fails with the following message:

```
-- Unit nfs-idmapd.service has begun starting up.
Mar 11 20:39:17 ip-172-31-0-41 rpc.idmapd[4681]: main: open(/var/lib/nfs/rpc_pipefs//nfs): No such file or directory
Mar 11 20:39:17 ip-172-31-0-41 systemd[1]: nfs-idmapd.service: control process exited, code=exited status=1
Mar 11 20:39:17 ip-172-31-0-41 systemd[1]: Failed to start NFSv4 ID-name mapping service.
-- Subject: Unit nfs-idmapd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit nfs-idmapd.service has failed.
```

Reproduction Steps:

1. Build `kola` from the following branch: https://github.com/arithx/mantle/tree/oscontainer_pivot
 • Adding `Manhole(m)` before [this line](https://github.com/arithx/mantle/blob/oscontainer_pivot/platform/platform.go#L351) in `platform/platform.go` is useful for additional debugging
2. `kola -p aws --aws-ami $ami --oscontainer $oscontainer -b rhcos run $test` where `$test` is either `coreos.ignition.systemd.enable-service` or `linux.nfs.v4`

Additional info noticed:

 - The `Source` in `findmnt` differs between a system that has performed the `pivot` and one that hasn't. On the `pivot` system it's `rpc_pipefs` while on the non-pivot system it's `sunrpc`.

**Comment by ashcrow** [comment] 2019-03-11 21:46
Thanks for the report @arithx!

**Comment by ashcrow** [comment] 2019-03-11 21:50
I've created a bug card so we make sure to debug.

**Comment by miabbott** [comment] 2019-03-12 20:19
I reproduced this using the instructions above:

`$ bin/kola --aws-profile openshift-dev --aws-ami ami-055533d626f74500c -d -p aws --aws-type t2.small --aws-region us-west-2 --oscontainer registry.svc.ci.openshift.org/rhcos/maipo:latest -b rhcos run coreos.ignition.systemd.enable-service`

Been combing the journal looking for a smoking gun, but nothing conclusive.

Saw this in the journal after the `pivot` completed and the node was being rebooted, but I don't think it is necessarily related:

```
Mar 12 19:39:02 ip-172-31-15-118 systemd[1]: Found ordering cycle on local-fs.target/stop
Mar 12 19:39:02 ip-172-31-15-118 systemd[1]: Found dependency on var-lib-nfs-rpc_pipefs.mount/stop
Mar 12 19:39:02 ip-172-31-15-118 systemd[1]: Found dependency on systemd-tmpfiles-setup.service/stop
Mar 12 19:39:02 ip-172-31-15-118 systemd[1]: Found dependency on local-fs.target/stop
Mar 12 19:39:02 ip-172-31-15-118 systemd[1]: Breaking ordering cycle by deleting job var-lib-nfs-rpc_pipefs.mount/stop
Mar 12 19:39:02 ip-172-31-15-118 systemd[1]: Job var-lib-nfs-rpc_pipefs.mount/stop deleted to break ordering cycle starting with local-fs.target/stop
Mar 12 19:39:02 ip-172-31-15-118 systemd[1]: Stopping RPC bind service...
```

**Comment by miabbott** [comment] 2019-03-12 20:34
There were some hits on Bugzilla for this space (i.e `nfs/rpc_pipefs`) but everything seems to be fixed.  

For example:  https://bugzilla.redhat.com/show_bug.cgi?id=1219871

**Comment by miabbott** [comment] 2019-03-12 20:57
Booting the old version (`400.7.20190301.0`) and new version (`400.7.20190306.0`) on their own shows that the `/var/lib/nfs/rpc_pipefs//nfs` directory is correctly set up in both cases.  It seems that only after the `pivot` is it failing.

I'd be interested to see if the failure is reproducible pivoting from `400.7.20190306.0` to a newer version.

**Comment by jlebon** [comment] 2019-03-12 21:32
>  It seems that only after the pivot is it failing.

Hmm, that's pretty odd. I suspect it's related to some state in `/var` being carried over. Although... does it still work if you boot just the new version on its own and reboot multiple times? Might just be related to whether `systemd-tmpfiles` ran at least once.

**Comment by miabbott** [comment] 2019-03-13 12:59
> Although... does it still work if you boot just the new version on its own and reboot multiple times?

I didn't get that far, but I will test this out today.

**Comment by miabbott** [comment] 2019-03-13 14:03
@jlebon was on the right trail.  After rebooting an RHCOS host one or more times, the `/var/lib/nfs/rpc_pipefs` directory is left empty.

```
$ rpm-ostree status
State: idle
Warning: failed to query journal: Cannot assign requested address (os error 99)
AutomaticUpdates: disabled
Deployments:
● pivot://docker-registry-default.cloud.registry.upshift.redhat.com/redhat-coreos/maipo@sha256:c09f455cc09673a1a13ae7b54cc4348cda0411e06dfa79ecd0130b35d62e8670
              CustomOrigin: Provisioned from oscontainer
                   Version: 400.7.20190306.0 (2019-03-06T22:16:26Z)
[core@ip-172-18-6-221 ~]$ sudo journalctl --list-boots
-2 c8358e13b6484506b2fe41209a9efda3 Wed 2019-03-13 13:48:24 UTC—Wed 2019-03-13 13:52:21 UTC
-1 bcafe80c64d747a981d784c9f07e8010 Wed 2019-03-13 13:52:46 UTC—Wed 2019-03-13 13:56:16 UTC
 0 cffcca3277674fd7bf8ee41a46b5cf94 Wed 2019-03-13 13:56:40 UTC—Wed 2019-03-13 13:58:45 UTC
[core@ip-172-18-6-221 ~]$ ls -laZ /var/lib/nfs/rpc_pipefs
dr-xr-xr-x. root root system_u:object_r:unlabeled_t:s0 .
drwxr-xr-x. root root system_u:object_r:var_lib_nfs_t:s0 ..
```

**Comment by jlebon** [comment] 2019-03-13 15:48
OK, so before we dig in more here: do we actually care about maipo at this point? Does the test also fail on ootpa?

**Comment by miabbott** [comment] 2019-03-13 16:02
So there's a `tmpfiles` entry for `/var/lib/nfs/rpc_piepfs`:

```
$ grep rpc_pipefs /usr/lib/tmpfiles.d/pkg-nfs-utils.conf
d /var/lib/nfs/rpc_pipefs 0555 root root - -
```

And I've only found this comment that explains how the subdirectories are created:

http://git.linux-nfs.org/?p=steved/nfs-utils.git;a=blob;f=utils/gssd/gssd.c;h=19ad4da5391afc8f08460a13da2a417aca97bb4a;hb=HEAD#l114

```
 * Directory structure: created by the kernel
 *      {rpc_pipefs}/{topdir}/clntXX      : one per rpc_clnt struct in the kernel
 *      {rpc_pipefs}/{topdir}/clntXX/krb5 : read uid for which kernel wants
 *					    a context, write the resulting context
 *      {rpc_pipefs}/{topdir}/clntXX/info : stores info such as server name
 *      {rpc_pipefs}/{topdir}/clntXX/gssd : pipe for all gss mechanisms using
 *					    a text-based string of parameters
```

But I still don't fully understand how all the subdirs are being created (or not created) in this case:

```
$ ls -laZ /var/lib/nfs/rpc_pipefs/
dr-xr-xr-x. root root system_u:object_r:rpc_pipefs_t:s0 .
drwxr-xr-x. root root system_u:object_r:var_lib_nfs_t:s0 ..
dr-xr-xr-x. root root system_u:object_r:rpc_pipefs_t:s0 cache
dr-xr-xr-x. root root system_u:object_r:rpc_pipefs_t:s0 gssd
dr-xr-xr-x. root root system_u:object_r:rpc_pipefs_t:s0 lockd
dr-xr-xr-x. root root system_u:object_r:rpc_pipefs_t:s0 mount
dr-xr-xr-x. root root system_u:object_r:rpc_pipefs_t:s0 nfs
dr-xr-xr-x. root root system_u:object_r:rpc_pipefs_t:s0 nfsd
dr-xr-xr-x. root root system_u:object_r:rpc_pipefs_t:s0 nfsd4_cb
dr-xr-xr-x. root root system_u:object_r:rpc_pipefs_t:s0 portmap
dr-xr-xr-x. root root system_u:object_r:rpc_pipefs_t:s0 statd
```

**Comment by miabbott** [comment] 2019-03-13 17:48
> Does the test also fail on ootpa?

Thanks for reminding me that we can ignore `maipo`.  :grinning: 

I'll switch to checking `ootpa` now...

**Comment by miabbott** [comment] 2019-03-13 18:20
Switching to `ootpa` didn't improve the situation; I'm still seeing the missing subdirs under `/var/lib/nfs/rpc_pipefs/` after a reboot.

Going down the path of `findmnt`, I see the following on first boot:

```
$ findmnt | grep var
├─/var                                  /dev/xvda3[/ostree/deploy/rhcos/var]                                                                           xfs        rw,relatime,seclabel,attr2,inode64,prjquota
│ ├─/var/lib/nfs/rpc_pipefs             rpc_pipefs                                                                                                     rpc_pipefs rw,relatime
│ └─/var/lib/containers/storage/overlay /dev/xvda3[/ostree/deploy/rhcos/var/lib/containers/storage/overlay]                                            xfs        rw,relatime,seclabel,attr2,inode64,prjquota
```

And then on subsequent boots:

```
$ findmnt | grep var
├─/var/lib/nfs/rpc_pipefs               rpc_pipefs                                                                                                     rpc_pipefs rw,relatime
├─/var                                  /dev/xvda3[/ostree/deploy/rhcos/var]                                                                           xfs        rw,relatime,seclabel,attr2,inode64,prjquota
│ └─/var/lib/containers/storage/overlay /dev/xvda3[/ostree/deploy/rhcos/var/lib/containers/storage/overlay]                                            xfs        rw,relatime,seclabel,attr2,inode64,prjquota
```

I don't know if it is a red herring that `/var/lib/nfs/rpc_pipefs` is not listed under `/var`, but just sharing things that look odd.

**Comment by mike-nguyen** [comment] 2019-03-14 20:14
These look interesting/relevant.  I haven't had a chance to dig in deeper but leaving the links here just in case I lose my tabs.

- https://bugzilla.redhat.com/show_bug.cgi?id=1406164
- https://src.fedoraproject.org/cgit/rpms/nfs-utils.git/commit/?id=feea4f146dc282fcea12feb8085e7bd9ff7abd6a
- https://github.com/projectatomic/rpm-ostree/blob/adff1e98b6b99e7940112846a968b802bdcf68af/src/libpriv/rpmostree-postprocess.c#L496
- https://github.com/projectatomic/rpm-ostree/pull/1229
- https://bugzilla.redhat.com/show_bug.cgi?id=1427537

**Comment by jlebon** [comment] 2019-03-14 20:45
Hmm, OK yeah I can reproduce this locally. I'm still piecing things together, but I think this is related to [`ignition-ask-var-mount.service`](https://github.com/coreos/ignition-dracut/blob/d4e8899c91302a887e157fe2142bc1342f473c89/dracut/30ignition/ignition-ask-var-mount.service).

**Comment by jlebon** [comment] 2019-03-14 20:59
https://url.corp.redhat.com/ed36825

**Comment by miabbott** [comment] 2019-03-15 17:37
I confirmed this fixes the problem in the reboot case, using the fix for the RHCOS pipeline.

I would like to verify the `kola` tests work when pointing at an updated `oscontainer` before closing this.

Thanks again @jlebon for the investigation + fix!

**Comment by miabbott** [comment] 2019-03-27 21:04
Finally got around to re-testing the failed cases using `--oscontainer` and can confirm they are passing again.  Went from RHCOS `410.8.20190325.0` to `410.8.20190326.0`

**Closed by miabbott** 2019-03-27 21:04 UTC
