### ISSUE TITLE
How to handle Ignition first-boot detection

### ISSUE THREAD

**Issue by dgonyeo** [openshift/os#73] opened 2018-05-31 20:33 UTC
Located here for lack of a better location to put this issue up.

Ignition should only run once. On CL today this is handled by detecting a file on the boot partition in the [grub config](https://github.com/coreos/scripts/blob/1bd0c0cd94aa4f8f6c11c3fb723f1c128637c83c/build_library/grub.cfg#L69). If this file is noticed a kernel command line argument is set, which a systemd generator in the initrd notices and then enables the Ignition units. One of these units then deletes the file once Ignition succeeds.

The way I see it there are two main options for achieving this in red hat land:

## Detect a file on the boot partition via the grub config

Similar (identical, really) logic as CL could be used in the grub config of RHCOS to trigger Ignition. Additionally it's really straightforward to enable networking in the initrd by adding some kernel command line arguments, so adding those only when Ignition is going to run would be easy.

The biggest downside I see is that this solution becomes much trickier to implement in an RPM for a system that doesn't include Ignition by default (e.g. Fedora). Modifying the grub config for the sake of Ignition on those platforms seems like a bad idea, so if RHCOS goes with this solution a different one will need to be devised for Fedora/etc.

## Detect a file on the boot partition via Ignition's systemd generator

A systemd generator is used in the initrd to determine if Ignition should run. This generator could look for the file on the boot partition itself, and enable the network and Ignition when its present.

The downsides of this are:
- I already tried this, but the generator was failing for reasons I don't understand. I may have simply had a programming error, but the generator would succeed when manually run from an emergency shell, so I think the generators run early enough to be racing with udev.
- The generator needs to be able to find the boot partition, so we'll need to mandate that the boot partition has a well known label (e.g. `boot`). Such a mandate may not be possible on other platforms such as Fedora.
- I have yet to find a reasonable way to start the network once the initrd is running. Finding someone more experienced with dracut may make this a non-issue.

---

I'd love people's thoughts on this, especially on if I'm missing any other big positives/negatives for this approach or if we should strive to keep the RHCOS run-Ignition-once solution the same as we use on other platforms.

**Comment by ashcrow** [comment] 2018-05-31 20:40
> Detect a file on the boot partition via Ignition's systemd generator

To me this is the more attractive option. I'd like to have unified `ignition` usage between Fedora/etc.. and CoreOS. Is the testing artifacts you used available somewhere that others could poke around and see if they notice what's breaking?

**Comment by cgwalters** [comment] 2018-05-31 20:41
On CL today does it modify the bootloader commandline, or is state stored in the partition table?

If a boot partition exists today in a Fedora-derived system (including FAH, although [ostree+grub2 kind of requires a /boot partition](https://github.com/ostreedev/ostree/issues/1452)), indeed it's mounted by the post-bootloader as part of the normal `/etc/fstab` processing in post-switchroot.  Nothing by default is going to mount it beforehand.

My vote would be to store the "booted" state in `/etc` somewhere - it's guaranteed to be on the rootfs, and mounting that is the whole point of the initrd.  So, `/etc/ignition.booted` or something?

**Comment by bgilbert** [comment] 2018-05-31 22:49
Here's [what CL is doing today](https://github.com/coreos/scripts/blob/1bd0c0cd94aa4f8f6c11c3fb723f1c128637c83c/build_library/grub.cfg#L68-L71).

Storing a flag file in `/etc` could work.  In general I think it's slightly better to remove a flag file than to add one (since people might be more tempted to delete an existing file to try to rerun Ignition) but that approach may not make sense here.

**Comment by ashcrow** [comment] 2018-06-06 19:29
Any other comments before we come to a conclusion on this?

**Comment by dustymabe** [comment] 2018-06-06 19:29
> My vote would be to store the "booted" state in /etc somewhere

I think this might be problematic because of `ignition-disks.service` which i think needs to run before the root filesystem is mounted.

**Comment by cgwalters** [comment] 2018-06-06 19:34
> I think this might be problematic because of ignition-disks.service which i think needs to run before the root filesystem is mounted.

But we only need that if we're replacing the rootfs, which we can't do on either classic or ostree right?

**Comment by cgwalters** [comment] 2018-06-06 19:38
Though going back to the top...storing the state in `/boot` seems OK by me too.  (Although we have future plans for ostree-based systems to make `/boot` ro by default, we can trivially teach ignition how to temporarily make it writable).

Changing the grub config really shouldn't be a problem at all for {F,RH}CoreOS - wouldn't it work to just drop an `/etc/grub.d/14_ignition` or so?

**Comment by ashcrow** [comment] 2018-06-06 19:53
> Changing the grub config really shouldn't be a problem at all for {F,RH}CoreOS - wouldn't it work to just drop an /etc/grub.d/14_ignition or so?

I'd think that would work. I'd avoid adding it into `grub2-tools` for now, but added in via an `ignition` package.

**Comment by cgwalters** [comment] 2018-06-06 22:21
> But we only need that if we're replacing the rootfs, which we can't do on either classic or ostree right?

To elaborate slightly...I can imagine supporting this but I find the usage scenarios confusing.  If you e.g. want to make the rootfs RAID1 (or whatever, change the rootfs storage in any way)...isn't that more like an "installer" path like that exists today with Anaconda as well as [coreos-install](https://coreos.com/os/docs/latest/installing-to-disk.html) ?

**Comment by dgonyeo** [comment] 2018-06-06 23:13
@cgwalters `coreos-install` is just a glorified `dd`, any operations changing the disks is done by Ignition.

Dropping something in `/etc/grub.d` could also be viable, I wasn't actually aware of that directory when I wrote this issue.

**Comment by ashcrow** [comment] 2018-06-07 13:37
Are we close to coming to a conclusion or should we meet in BJN to help close this decision out?

**Comment by dustymabe** [comment] 2018-06-07 13:39
> wouldn't it work to just drop an /etc/grub.d/14_ignition or so

Do you have an example of what exactly would be in this file?

**Comment by ashcrow** [comment] 2018-06-07 13:57
Something similar to what ContainerLinux does today but probably much simpler since it's a drop in rather than a full `grub.conf`:

```shell

#!/bin/sh
set -e

IGNITION_CHECK_FILE=/boot/ignition_has_run
set first_boot=""

# If the file exists
if [ -f "${IGNITION_CHECK_FILE}" ]; then
     set first_boot="coreos.first_boot=detected"
fi

# TODO: Append or add to menu arguments
```

**Comment by ashcrow** [comment] 2018-06-07 19:38
If no one objects, why don't we follow the "Detect a file on the boot partition via the grub config" path then using the ` /etc/grub.d/XX_ignition` path.

Any objections?

**Comment by dgonyeo** [comment] 2018-06-07 19:52
That works for me. If unexpected difficulties come up there's nothing stopping us from attempting the other approach later.

**Comment by ashcrow** [comment] 2018-06-11 15:35
We'll run with: Detect a file on the boot partition via the grub config" path then using the /etc/grub.d/XX_ignition path.

**Closed by ashcrow** 2018-06-11 15:35 UTC

**Comment by bgilbert** [comment] 2018-06-11 20:57
@cgwalters:
> If you e.g. want to make the rootfs RAID1 (or whatever, change the rootfs storage in any way)...isn't that more like an "installer" path like that exists today with Anaconda as well as coreos-install ?

The general idea is: since cloud images have to be able to provision themselves anyway, without the aid of an installer, all other platforms might as well do the same.

**Comment by cgwalters** [comment] 2018-06-20 15:07
@ashcrow Why did we close this?  The issue is still open right?

**Comment by dustymabe** [comment] 2018-06-20 15:12
i think there is another issue open that chose an implementation and ran with it

**Comment by ashcrow** [comment] 2018-06-20 15:27
@cgwalters nope, this was closed out with a decision in https://github.com/openshift/os/issues/73#issuecomment-396286746.
