### ISSUE TITLE
c9s: ext.config.shared.ignition.resource.remote started failing

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#1187] opened 2023-03-09 13:48 UTC
> 08:16:04    ignition-2.15.0-1.el9.x86_64 (appstream)
> ...
> 08:30:39  --- FAIL: ext.config.shared.ignition.resource.remote (6.55s)
> 08:30:39          harness.go:1642: mach.Start() failed: machine 92acf525-eb20-4023-8f3a-8a61c2880dbf entered emergency.target in initramfs

```
[    3.058090] ignition[693]: failed to fetch config: unsupported config version
[    3.058654] ignition[693]: failed to acquire config: unsupported config version
[    3.059189] ignition[693]: Ignition failed: unsupported config version
[[0;1;31mFAILED[0m] Failed to start [0;1;39mIgnition (fetch-offline)[0m.
See 'systemctl status ignition-fetch-offline.service' for details.
[[0;1;38;5;185mDEPEND[0m] Dependency failed for [0;1;39mIgnition Complete[0m.
[[0;1;38;5;185mDEPEND[0m] Dependency failed for [0;1;39mInitrd Default Target[0m.
[[0;32m  OK  [0m] Stopped target [0;1;39mInitrd /usr File System[0m.[    3.064433] systemd[1]: ignition-fetch-offline.service: Main process exited, code=exited, status=1/FAILURE
[    3.065106] systemd[1]: ignition-fetch-offline.service: Failed with result 'exit-code'.
```

**Comment by cgwalters** [comment] 2023-03-09 13:54
Seems this is a regression, our previous run used `ignition-2.14.0-5.rhaos4.12.el9.x86_64 `

**Comment by travier** [comment] 2023-03-09 13:56
Looks like https://github.com/coreos/fedora-coreos-config/pull/2268

**Comment by travier** [comment] 2023-03-09 13:56
But agree that we should be using Ignition from C9S. I think we still waiting for a new compose with the latest one from it :/

**Comment by travier** [comment] 2023-03-09 13:57
https://composes.stream.centos.org/production/latest-CentOS-Stream/compose/AppStream/x86_64/os/Packages/ignition-2.15.0-1.el9.x86_64.rpm > It should be there now. Wondering why we're not picking it from there.

**Comment by travier** [comment] 2023-03-09 14:00
I had asked ART to untag those pacakges in https://issues.redhat.com/browse/ART-6055 but looks like one sneaked in again?

**Comment by cgwalters** [comment] 2023-03-09 14:00
Argh, the snooze thing sometimes feels like a self-inflicted footgun.  

We *are* picking up that ignition version now, that's apparently the problem?  Or, maybe you're right in that actually we just need to pick up the snooze?  Looks like it's in https://github.com/openshift/os/pull/1185

**Comment by travier** [comment] 2023-03-09 14:02
We won't pick the snooze from the fcos bump as we don't the denylist from the submodule AFAIK

**Comment by travier** [comment] 2023-03-09 14:09
https://github.com/openshift/os/pull/1188 > This one should force ignition to come from C9S.

**Comment by bgilbert** [comment] 2023-03-09 18:05
The problem is that we are correctly picking up the C9S version of Ignition, the snooze has been correctly synced into the fedora-coreos-config submodule, but the snooze isn't being respected.

**Comment by bgilbert** [comment] 2023-03-09 18:28
Now that https://github.com/coreos/butane/pull/435 landed I think we can just bump coreos-assembler.  Working on it.

**Comment by bgilbert** [comment] 2023-03-09 18:47
Let's try https://github.com/coreos/coreos-assembler/pull/3387.

**Closed** 2023-03-09 22:03 UTC
